### ISSUE TITLE
No Firefox Version!? Firefox version needed!! Firefox is the best!

### ISSUE THREAD

**Issue by JaydenDev** [gosoccerboy5/translate-text#2]
Please make a Firefox version

**Comment by JaydenDev** [comment]
> 
> 
> Ok, I do want to cater to firefox users. I don't know the mozilla browser extension APIs, though. Maybe when I get some time.

I am attempting to make a port right now, I made a fork and am reading some documentation. If you wanna help, you can make some pull requests.

**Comment by JaydenDev** [comment]
Update: Error is unsupported manifest version: 3

**Comment by gosoccerboy5** [comment]
I made it available to Firefox users (only as a temporary addon tho).
Tell me what you think..

**Comment by jdev082** [comment]
Works great! Shows up in the context menu, opens the window. It works!

![image](https://user-images.githubusercontent.com/92550746/137594688-bb75b5a4-21fd-42a0-ac9f-17f75f16b002.png)

**Comment by gosoccerboy5** [comment]
Nice.
